apiVersion: v1
kind: Pod
metadata:
  name: hugepage-2c-1p
spec:
  containers:
  - name: container-1
    image: ubuntu:latest
    command:
    - sleep
    - inf
    volumeMounts:
    - mountPath: /hugepages
      name: hugepage
    - mountPath: /root/dpdk
      name: dpdk
    - mountPath: /lib/aarch64-linux-gnu
      name: lib
    - mountPath: /var/run/dpdk
      name: dpdk-config
    resources:
      limits:
        hugepages-2Mi: 10Mi
        memory: 100Mi
      requests:
        memory: 100Mi
  - name: container-2
    #image: fedora:latest
    #image: centos:latest
    image: ubuntu:latest
    command:
    - sleep
    - inf
    volumeMounts:
    - mountPath: /hugepages
      name: hugepage
    - mountPath: /root/dpdk
      name: dpdk
    - mountPath: /lib/aarch64-linux-gnu
      name: lib
    - mountPath: /var/run/dpdk
      name: dpdk-config
    resources:
      limits:
        hugepages-2Mi: 10Mi
        memory: 100Mi
      requests:
        memory: 100Mi
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
  - name: dpdk-config
    emptyDir:
  - name: dpdk
    hostPath:
      path: /home/cychong/tmp/dpdk-21.11/build/examples
      type: Directory
  - name: lib
    hostPath:
      path: /lib/aarch64-linux-gnu
      type: Directory
